version: '3.3'
services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
    - .:/app
    environment:
      - MANAGED=${MANAGED}
      - SECRET_KEY=${SECRET_KEY}
      - REQUIRE_PERMISSION_CHECK=${REQUIRE_PERMISSION_CHECK}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DATABASE_URL=${DATABASE_URL}