# Generated by Django 3.2.12 on 2022-03-03 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sql'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pregunta',
            unique_together={('texto', 'tema', 'numero_pregunta')},
        ),
    ]
