# Generated by Django 3.2.15 on 2022-08-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sql'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='nivel',
            field=models.CharField(choices=[('Basico', 'Basico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default='Basico', max_length=255),
        ),
    ]
