# Generated by Django 3.2.15 on 2022-08-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sql'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('Opción múltiple', 'Opción múltiple'), ('Complementar', 'Complementar')], default='Opción múltiple', max_length=255),
        ),
    ]
